// <auto-generated />
using AccountingSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AccountingSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251010120000_AddCurrencyBreakdowns")]
    partial class AddCurrencyBreakdowns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            new Snapshot().BuildModelSnapshot(modelBuilder);
#pragma warning restore 612, 618
        }

        private sealed class Snapshot : ApplicationDbContextModelSnapshot
        {
            public void BuildModelSnapshot(ModelBuilder modelBuilder)
            {
                base.BuildModel(modelBuilder);
            }
        }
    }
}
