// <auto-generated />
using System;
using AccountingSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountingSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251202010000_AddAgentsModule")]
    partial class AddAgentsModule
    {
        private sealed class Snapshot : ApplicationDbContextModelSnapshot
        {
            public void BuildSnapshotModel(ModelBuilder modelBuilder)
            {
                base.BuildModel(modelBuilder);
            }
        }

        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            new Snapshot().BuildSnapshotModel(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
